steps:
  - label: ":nix::point_right::pipeline:"
    command: |
      export NIX_PATH="nixpkgs=$(nix eval --impure --raw --expr '(import nix/sources.nix).nixpkgs')"
      nix eval --impure --json --expr '(import ./.buildkite { pipeline = ./.buildkite/pipeline.nix; })' \
      | buildkite-agent pipeline upload --no-interpolation

    agents:
      queue: project42
